/* eslint-disable @typescript-eslint/ban-ts-comment */
import type { Metadata } from "next";
import { Exo } from 'next/font/google'
// @ts-ignore
import "./globals.css";
import { LanguageProvider } from './context/LanguageContext';


const exo = Exo({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Portifolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="pt-br" >
      <body className={exo.className}>
               <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
