import type { Metadata } from "next";
import { Exo } from 'next/font/google'
import "./globals.css";

const exo = Exo({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Portifolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="pt-br" >
      <body className={exo.className}>
        {children}
      </body>
    </html>
  );
}
